/* Shared build logic, used by build.js (Node) and build.html (browser).
   Splits exam-master.js into a public question file (no answers) and a private answer key. */
(function (root) {
  function hash(s) { var h = 2166136261; for (var i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); } return (h >>> 0).toString(36); }
  function optId(pid, i, text, used) { var id = 'o' + hash(pid + '|' + i + '|' + text).slice(0, 4); while (used[id]) id += 'x'; used[id] = 1; return id; }

  function buildOutputs(M) {
    var problems = [], ids = {}, keyParts = [], total = 0;
    var pubQuestions = M.questions.map(function (q) {
      var pq = { num: q.num, section: q.section };
      ['stem', 'listing', 'figure'].forEach(function (k) { if (q[k] != null) pq[k] = q[k]; });
      pq.parts = q.parts.map(function (p) {
        if (ids[p.id]) problems.push('Duplicate part id ' + p.id); ids[p.id] = 1;
        var full = 'Q' + q.num + (p.label || '');
        var pub = { id: p.id, label: p.label || '', type: p.type, marks: p.marks, prompt: p.prompt };
        ['lead', 'listing', 'grid', 'code', 'template', 'columns'].forEach(function (k) { if (p[k] != null) pub[k] = p[k]; });
        var key, used = {};
        switch (p.type) {
          case 'mcq':
            pub.options = p.options.map(function (o, i) { var x = { id: optId(p.id, i, o.text, used), text: o.text }; if (o.html) x.html = o.html; if (o.code) x.code = true; return x; });
            if (!(p.correct >= 0 && p.correct < p.options.length)) problems.push(full + ': correct index out of range');
            key = pub.options[p.correct] && pub.options[p.correct].id; break;
          case 'select':
            var n = (p.template.match(/\{\{\d+\}\}/g) || []).length;
            if (n !== p.gaps.length) problems.push(full + ': template has ' + n + ' gaps but ' + p.gaps.length + ' are defined');
            pub.gaps = p.gaps.map(function (g) { if (g.options.indexOf(g.ans) < 0) problems.push(full + ': answer "' + g.ans + '" is not one of the options'); return { options: g.options }; });
            key = p.gaps.map(function (g) { return g.ans; }); break;
          case 'tick':
            pub.rows = p.rows.map(function (r) { return { text: r.text }; });
            key = p.rows.map(function (r) { return r.ans; }); break;
          case 'match':
            pub.options = p.options; pub.items = p.items.map(function (it) { return { text: it.text }; });
            key = p.items.map(function (it) { return it.ans; }); break;
          case 'order':
            var items = p.items.map(function (t, i) { return { id: optId(p.id, i, t, used), text: t }; });
            key = items.map(function (it) { return it.id; });
            pub.items = items.slice().sort(function (a, b) { return a.text < b.text ? -1 : 1; }); break;
          case 'bits':
            if (!/^[01]{4,16}$/.test(p.ans)) problems.push(full + ': bits answer must be 4 to 16 characters of 0/1');
            key = p.ans; pub.n = p.ans.length; if (p.hint) pub.hint = p.hint; if (p.group) pub.group = p.group; break;
          case 'errline':
            pub.lines = p.lines; key = p.ans;
            if (!(p.ans >= 0 && p.ans < p.lines.length)) problems.push(full + ': ans line out of range'); break;
          default: problems.push(full + ': unknown type ' + p.type);
        }
        total += p.marks;
        keyParts.push({ id: p.id, qnum: q.num, full: full, type: p.type, marks: p.marks, section: q.section, skill: p.skill, topic: p.topic,
          key: key, answer: p.answer || '', explain: p.explain || '', scoring: p.scoring });
        return pub;
      });
      return pq;
    });
    var meta = M.meta;
    var pub = { meta: meta, sections: M.sections, skills: M.skills, questions: pubQuestions };
    var KEY = { meta: { testId: meta.testId, title: meta.title, course: meta.course, year: meta.year, subject: meta.subject || 'Computing', durationMinutes: meta.durationMinutes, gradeBoundaries: meta.gradeBoundaries },
      sections: M.sections, skills: M.skills, parts: keyParts };
    var bySec = {}; keyParts.forEach(function (p) { bySec[p.section] = (bySec[p.section] || 0) + p.marks; });
    var stamp = new Date().toISOString().slice(0, 16).replace('T', ' ');
    return {
      questionsJs: '/* Generated by the build on ' + stamp + ' — do not edit. Questions only: no answers are in this file. */\nwindow.EXAM = ' + JSON.stringify(pub) + ';\n',
      keyGs: '/* Generated by the build on ' + stamp + ' — ANSWER KEY. Keep private: paste into Apps Script only. */\nvar ANSWER_KEY = ' + JSON.stringify(KEY, null, 1) + ';\n',
      total: total, questionCount: M.questions.length, partCount: keyParts.length, bySection: bySec, problems: problems
    };
  }
  root.buildOutputs = buildOutputs;
})(typeof window !== 'undefined' ? window : globalThis);
