/* Generated by the build on 2026-09-30 13:12 — ANSWER KEY. Keep private: paste into Apps Script only. */
var ANSWER_KEY = {
 "meta": {
  "testId": "y10-cs-progress-test-1",
  "title": "Progress Test 1",
  "course": "Cambridge IGCSE Computer Science (0478)",
  "year": "Year 10",
  "subject": "Computer Science",
  "durationMinutes": 35,
  "gradeBoundaries": [
   {
    "grade": "A*",
    "min": 78
   },
   {
    "grade": "A",
    "min": 62
   },
   {
    "grade": "B",
    "min": 46
   },
   {
    "grade": "C",
    "min": 30.7
   },
   {
    "grade": "D",
    "min": 26
   },
   {
    "grade": "E",
    "min": 21.3
   },
   {
    "grade": "F",
    "min": 16.7
   },
   {
    "grade": "G",
    "min": 12
   }
  ]
 },
 "sections": [
  {
   "id": "num",
   "name": "Number systems",
   "desc": "Binary, denary and hexadecimal, binary addition and overflow, logical shifts, two’s complement"
  },
  {
   "id": "media",
   "name": "Text, sound and images",
   "desc": "ASCII and Unicode, sampling, resolution and colour depth, file sizes"
  },
  {
   "id": "store",
   "name": "Storage and compression",
   "desc": "Storage units, 1024-based calculations, lossy and lossless compression, RLE"
  },
  {
   "id": "prog",
   "name": "Programming fundamentals",
   "desc": "Operators, string handling, tracing, loops, validation and CASE"
  },
  {
   "id": "arr",
   "name": "1D arrays",
   "desc": "Declaring and using 1D arrays, totalling and counting"
  }
 ],
 "skills": [
  {
   "id": "AO1",
   "name": "AO1 Knowledge and understanding"
  },
  {
   "id": "AO2",
   "name": "AO2 Applying knowledge"
  },
  {
   "id": "AO3",
   "name": "AO3 Designing algorithms"
  }
 ],
 "parts": [
  {
   "id": "1a",
   "qnum": 1,
   "full": "Q1(a)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Denary to binary",
   "key": "10110011",
   "answer": "<code>10110011</code>",
   "explain": "179 = 128 + 32 + 16 + 2 + 1."
  },
  {
   "id": "1b",
   "qnum": 1,
   "full": "Q1(b)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Hexadecimal to denary",
   "key": "o10gh",
   "answer": "62",
   "explain": "3 × 16 = 48 and E = 14. 48 + 14 = 62. (314 comes from writing 3 and 14 side by side.)"
  },
  {
   "id": "1c",
   "qnum": 1,
   "full": "Q1(c)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Binary to hexadecimal",
   "key": "orikz",
   "answer": "<code>D6</code>",
   "explain": "Split into nibbles: 1101 = 13 = D and 0110 = 6."
  },
  {
   "id": "1d",
   "qnum": 1,
   "full": "Q1(d)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Hexadecimal to binary",
   "key": "10011111",
   "answer": "<code>10011111</code>",
   "explain": "Convert each hex digit to 4 bits: 9 = 1001 and F (15) = 1111."
  },
  {
   "id": "1e",
   "qnum": 1,
   "full": "Q1(e)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO1",
   "topic": "Why hexadecimal is used",
   "key": "o1h5g",
   "answer": "It is shorter, so it is easier for people to read and there are fewer mistakes.",
   "explain": "Computers still store everything in binary: hexadecimal is only a shorter way for humans to write it."
  },
  {
   "id": "2a",
   "qnum": 2,
   "full": "Q2(a)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Binary addition",
   "key": "00010011",
   "answer": "<code>00010011</code> (the full answer is <code>1 0001 0011</code>, which needs 9 bits)",
   "explain": "182 + 93 = 275. Work right to left, carrying 1 whenever a column adds to 2 or 3."
  },
  {
   "id": "2b",
   "qnum": 2,
   "full": "Q2(b)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO1",
   "topic": "Overflow",
   "key": "opjn5",
   "answer": "Overflow",
   "explain": "An overflow error happens when a result is too big to fit in the register."
  },
  {
   "id": "2c",
   "qnum": 2,
   "full": "Q2(c)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO1",
   "topic": "Why overflow happens",
   "key": "otag0",
   "answer": "The result (275) is greater than 255, the largest value 8 bits can store.",
   "explain": "It needs a 9th bit that the register does not have."
  },
  {
   "id": "3a",
   "qnum": 3,
   "full": "Q3(a)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Logical left shift",
   "key": "10110000",
   "answer": "<code>10110000</code>",
   "explain": "Every bit moves two places left, the two left-most bits (00) are lost, and two 0s enter on the right."
  },
  {
   "id": "3b",
   "qnum": 3,
   "full": "Q3(b)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO1",
   "topic": "Effect of a left shift",
   "key": "o12cd",
   "answer": "It is multiplied by 4",
   "explain": "Each place left multiplies by 2, so two places = × 4. 44 becomes 176."
  },
  {
   "id": "3c",
   "qnum": 3,
   "full": "Q3(c)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Logical right shift",
   "key": "00000101",
   "answer": "<code>00000101</code>",
   "explain": "The three right-most bits (100) are lost and three 0s enter on the left. 44 ÷ 8 = 5.5, but the 0.5 is lost, so the result is 5."
  },
  {
   "id": "4a",
   "qnum": 4,
   "full": "Q4(a)",
   "type": "bits",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Negative denary to two’s complement",
   "key": "11010011",
   "answer": "<code>11010011</code>",
   "explain": "+45 = 00101101 → flip the bits = 11010010 → add 1 = 11010011. Check: −128 + 64 + 16 + 2 + 1 = −45."
  },
  {
   "id": "4b",
   "qnum": 4,
   "full": "Q4(b)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO2",
   "topic": "Two’s complement to denary",
   "key": "o1gx9",
   "answer": "−102",
   "explain": "−128 + 16 + 8 + 2 = −102. (154 is the unsigned value.)"
  },
  {
   "id": "4c",
   "qnum": 4,
   "full": "Q4(c)",
   "type": "mcq",
   "marks": 1,
   "section": "num",
   "skill": "AO1",
   "topic": "Most significant bit in two’s complement",
   "key": "o1rmc",
   "answer": "It has a place value of −128, so the number is negative when the MSB is 1.",
   "explain": ""
  },
  {
   "id": "5",
   "qnum": 5,
   "full": "Q5",
   "type": "tick",
   "marks": 2,
   "section": "media",
   "skill": "AO1",
   "topic": "ASCII and Unicode",
   "key": [
    1,
    0,
    2,
    1
   ],
   "answer": "Unicode; ASCII; Both; Unicode",
   "explain": "2 marks for 4 correct, 1 mark for 2 or 3 correct. Unicode has far more characters, so it needs more bits per character."
  },
  {
   "id": "6a",
   "qnum": 6,
   "full": "Q6(a)",
   "type": "match",
   "marks": 2,
   "section": "media",
   "skill": "AO1",
   "topic": "Sound and image key terms",
   "key": [
    2,
    0,
    1,
    3
   ],
   "answer": "Sample rate → samples each second; sample resolution → bits per sample; image resolution → number of pixels; colour depth → bits per pixel",
   "explain": ""
  },
  {
   "id": "6b",
   "qnum": 6,
   "full": "Q6(b)",
   "type": "select",
   "marks": 2,
   "section": "media",
   "skill": "AO2",
   "topic": "Sound file-size calculation",
   "key": [
    "1 280 000",
    "156.25"
   ],
   "answer": "1 280 000 bits; 156.25 KiB",
   "explain": "8000 × 16 × 10 = 1 280 000 bits → ÷ 8 = 160 000 bytes → ÷ 1024 = 156.25 KiB."
  },
  {
   "id": "6c",
   "qnum": 6,
   "full": "Q6(c)",
   "type": "tick",
   "marks": 2,
   "section": "media",
   "skill": "AO1",
   "topic": "Effect of increasing the sample rate",
   "key": [
    0,
    0,
    1,
    1
   ],
   "answer": "True; True; False; False",
   "explain": "More samples = better accuracy but a larger file. More bits per sample is the sample resolution, not the rate."
  },
  {
   "id": "7a",
   "qnum": 7,
   "full": "Q7(a)",
   "type": "select",
   "marks": 2,
   "section": "media",
   "skill": "AO2",
   "topic": "Image file-size calculation",
   "key": [
    "1 440 000",
    "1 406.25"
   ],
   "answer": "1 440 000 bytes; 1 406.25 KiB",
   "explain": "800 × 600 = 480 000 pixels × 24 bits = 11 520 000 bits → ÷ 8 = 1 440 000 bytes → ÷ 1024 = 1 406.25 KiB."
  },
  {
   "id": "7b",
   "qnum": 7,
   "full": "Q7(b)",
   "type": "mcq",
   "marks": 1,
   "section": "media",
   "skill": "AO1",
   "topic": "Effect of colour depth",
   "key": "ot78n",
   "answer": "The file size becomes one third of the original and fewer colours can be shown.",
   "explain": "8 ÷ 24 = one third. Fewer bits per pixel means fewer possible colours."
  },
  {
   "id": "8a",
   "qnum": 8,
   "full": "Q8(a)",
   "type": "select",
   "marks": 1,
   "section": "store",
   "skill": "AO1",
   "topic": "Storage units",
   "key": [
    "KiB",
    "PiB"
   ],
   "answer": "1 MiB = 1024 KiB; 1 EiB = 1024 PiB",
   "explain": "Order: bit, nibble, byte, KiB, MiB, GiB, TiB, PiB, EiB."
  },
  {
   "id": "8b",
   "qnum": 8,
   "full": "Q8(b)",
   "type": "mcq",
   "marks": 1,
   "section": "store",
   "skill": "AO2",
   "topic": "Storage calculation (1024-based)",
   "key": "odpm4",
   "answer": "512",
   "explain": "3 × 1024 = 3072 MiB. 3072 ÷ 6 = 512. (500 comes from using 1000.)"
  },
  {
   "id": "9a",
   "qnum": 9,
   "full": "Q9(a)",
   "type": "tick",
   "marks": 2,
   "section": "store",
   "skill": "AO1",
   "topic": "Why files are compressed",
   "key": [
    0,
    0,
    1,
    1
   ],
   "answer": "Good; Good; Not a reason; Not a reason",
   "explain": "Compression reduces file size, so transfers are quicker and use less bandwidth. It never improves quality and does not protect against malware."
  },
  {
   "id": "9b",
   "qnum": 9,
   "full": "Q9(b)",
   "type": "tick",
   "marks": 2,
   "section": "store",
   "skill": "AO1",
   "topic": "Lossy and lossless compression",
   "key": [
    0,
    1,
    1,
    0
   ],
   "answer": "Lossy; Lossless; Lossless; Lossy",
   "explain": ""
  },
  {
   "id": "9c",
   "qnum": 9,
   "full": "Q9(c)",
   "type": "mcq",
   "marks": 1,
   "section": "store",
   "skill": "AO2",
   "topic": "Run Length Encoding",
   "key": "o19fs",
   "answer": "<code>5A3B7C1D</code>",
   "explain": "5 As, 3 Bs, 7 Cs and 1 D. The single D still needs a count."
  },
  {
   "id": "10a",
   "qnum": 10,
   "full": "Q10(a)",
   "type": "select",
   "marks": 2,
   "section": "prog",
   "skill": "AO2",
   "topic": "Arithmetic operators (MOD, DIV, ^, /)",
   "key": [
    "2",
    "3",
    "16",
    "4.25"
   ],
   "answer": "MOD(17, 5) = 2; DIV(17, 5) = 3; 2 ^ 4 = 16; 17 / 4 = 4.25",
   "explain": "MOD gives the remainder, DIV gives the whole-number part of a division, ^ is \"to the power of\", / is normal division. 2 marks for 4 correct, 1 mark for 2 or 3."
  },
  {
   "id": "10b",
   "qnum": 10,
   "full": "Q10(b)",
   "type": "tick",
   "marks": 2,
   "section": "prog",
   "skill": "AO2",
   "topic": "Relational operators",
   "key": [
    0,
    1,
    0,
    0
   ],
   "answer": "TRUE; FALSE; TRUE; TRUE",
   "explain": "&lt;&gt; means \"not equal to\". 12 &lt;= 12 is TRUE. 12 MOD 7 = 5."
  },
  {
   "id": "10c",
   "qnum": 10,
   "full": "Q10(c)",
   "type": "select",
   "marks": 2,
   "section": "prog",
   "skill": "AO2",
   "topic": "String handling (LENGTH, SUBSTRING, UCASE)",
   "key": [
    "16",
    "SCIENCE"
   ],
   "answer": "LENGTH(Word) = 16; UCASE(SUBSTRING(Word, 10, 7)) = \"SCIENCE\"",
   "explain": "The space counts as a character. SUBSTRING takes 7 characters starting at position 10; UCASE makes them upper case."
  },
  {
   "id": "11a",
   "qnum": 11,
   "full": "Q11(a)",
   "type": "select",
   "marks": 2,
   "section": "prog",
   "skill": "AO2",
   "topic": "Tracing a loop with a total and a counter",
   "key": [
    "12",
    "1",
    "12",
    "1",
    "32",
    "2",
    "32",
    "2",
    "47",
    "3"
   ],
   "answer": "Total: 12, 12, 32, 32, 47. Count: 1, 1, 2, 2, 3.",
   "explain": "Watch the input 10: 10 is not greater than 10, so nothing changes. 2 marks for all 10 cells, 1 mark for at least 5."
  },
  {
   "id": "11b",
   "qnum": 11,
   "full": "Q11(b)",
   "type": "mcq",
   "marks": 1,
   "section": "prog",
   "skill": "AO2",
   "topic": "Output of an algorithm",
   "key": "o4d6u",
   "answer": "<code>47 3</code>",
   "explain": "57 4 would be the output if 10 were counted (>= instead of >)."
  },
  {
   "id": "11c",
   "qnum": 11,
   "full": "Q11(c)",
   "type": "tick",
   "marks": 2,
   "section": "prog",
   "skill": "AO1",
   "topic": "Types of loop",
   "key": [
    0,
    1,
    2,
    1
   ],
   "answer": "Count-controlled; Pre-condition; Post-condition; Pre-condition",
   "explain": "A post-condition loop (REPEAT … UNTIL) always runs at least once."
  },
  {
   "id": "12",
   "qnum": 12,
   "full": "Q12",
   "type": "select",
   "marks": 2,
   "section": "prog",
   "skill": "AO3",
   "topic": "Validation loop and CASE statement",
   "key": [
    "REPEAT",
    "AND",
    "OF",
    "ENDCASE"
   ],
   "answer": "<code>REPEAT</code>, <code>AND</code>, <code>OF</code>, <code>ENDCASE</code>",
   "explain": "REPEAT … UNTIL is the loop that matches UNTIL. The choice must be at least 1 AND at most 3 (OR would accept anything). 2 marks for 4 correct, 1 mark for 2 or 3."
  },
  {
   "id": "13a",
   "qnum": 13,
   "full": "Q13(a)",
   "type": "mcq",
   "marks": 1,
   "section": "arr",
   "skill": "AO3",
   "topic": "Declaring a 1D array",
   "key": "o1g0c",
   "answer": "<code>DECLARE Names : ARRAY[1:30] OF STRING</code>",
   "explain": "Pattern: DECLARE name : ARRAY[lower:upper] OF type."
  },
  {
   "id": "13b",
   "qnum": 13,
   "full": "Q13(b)",
   "type": "mcq",
   "marks": 1,
   "section": "arr",
   "skill": "AO2",
   "topic": "Reading an element of a 1D array",
   "key": "os8me",
   "answer": "23",
   "explain": "The index is the position, starting at 1. (89 would be the answer if the index started at 0.)"
  },
  {
   "id": "13c",
   "qnum": 13,
   "full": "Q13(c)",
   "type": "mcq",
   "marks": 1,
   "section": "arr",
   "skill": "AO3",
   "topic": "Writing to an element of a 1D array",
   "key": "o11ym",
   "answer": "<code>Scores[3] ← 50</code>",
   "explain": "The array name and index go on the left of the arrow; the value goes on the right."
  },
  {
   "id": "14",
   "qnum": 14,
   "full": "Q14",
   "type": "select",
   "marks": 4,
   "section": "arr",
   "skill": "AO3",
   "topic": "Totalling, counting and averaging an array",
   "key": [
    "30",
    "Total + Scores[Index]",
    "Count + 1",
    "Total / 30"
   ],
   "answer": "<code>30</code>, <code>Total + Scores[Index]</code>, <code>Count + 1</code>, <code>Total / 30</code>",
   "explain": "Loop over all 30 elements; add each score to the total; add 1 to the counter for each score over 50; divide the total by the number of scores (30)."
  }
 ]
};
