/**
 * MBIS online test — marking server + results receiver
 * ------------------------------------------------------------------
 * The same Code.gs is used for every test. The Apps Script project has FOUR files:
 *   Settings.gs   (settings for this test: start code, emails, folder name)
 *   Code.gs       (this file — the web app; identical for every test)
 *   Marking.gs    (the marking engine — same code as site/marking.js)
 *   AnswerKey.gs  (the answers — generated by the build, keep private)
 *
 * What it does
 *   begin  → checks the start code and whether this email has already handed in,
 *            and logs the student on the "Started" tab.
 *   submit → marks the answers against ANSWER_KEY, logs a row on the "Results" tab
 *            and a row on the "By question" tab, and returns the marks + solutions.
 *   report → turns the results page and marked test into PDFs, emails them to the
 *            student and to you, and (optionally) saves them in a Drive folder.
 *
 * Setup: see README.md, step 2.
 */
/* Settings for this test are in Settings.gs. */

var HEAD = { navy: '#1B2B5E', white: '#FFFFFF' };
function TEST_NAME_() { return ANSWER_KEY.meta.year + ' ' + (ANSWER_KEY.meta.subject || 'Computing'); }

function doPost(e) {
  try {
    if (!e || !e.postData) return json_({ ok: false, error: 'No data was sent.' });
    var data = JSON.parse(e.postData.contents);
    if (data.key !== CONFIG.SHARED_KEY) return json_({ ok: false, error: 'Shared key does not match (check config.js and Code.gs).' });
    if (data.testId && data.testId !== ANSWER_KEY.meta.testId) return json_({ ok: false, error: 'This script has the answer key for "' + ANSWER_KEY.meta.testId + '", not "' + data.testId + '". Paste the new AnswerKey.gs and redeploy.' });
    if (data.action === 'ping') return json_({ ok: true, testId: ANSWER_KEY.meta.testId, marks: markSubmission(ANSWER_KEY, {}).max, startCode: !!CONFIG.START_CODE });
    if (data.action === 'begin') return json_(begin_(data));
    if (data.action === 'submit') return json_(submit_(data));
    if (data.action === 'report') return json_(report_(data));
    return json_({ ok: false, error: 'Unknown action.' });
  } catch (err) {
    console.error(err);
    return json_({ ok: false, error: String(err) });
  }
}

function doGet() { return json_({ ok: true, message: TEST_NAME_() + ' test server is running for ' + ANSWER_KEY.meta.testId + '.' }); }

/* ------------------------------------------------------------ begin */
function begin_(d) {
  var st = cleanStudent_(d.student);
  if (CONFIG.START_CODE && String(d.startCode || '').trim().toUpperCase() !== CONFIG.START_CODE.toUpperCase()) return { ok: false, code: 'startcode' };
  if (CONFIG.ONE_ATTEMPT_PER_EMAIL && attempts_(st.email) > 0) return { ok: false, code: 'already' };
  CacheService.getScriptCache().put('b_' + d.submissionId, String(Date.now()), 21600);
  withLock_(function () {
    var sh = sheet_(CONFIG.STARTED_SHEET, STARTED_HEADER_);
    sh.appendRow([new Date(), st.last, st.first, st.nick, st.email, d.submissionId, 'Not yet']);
  });
  return { ok: true };
}

/* ----------------------------------------------------------- submit */
function submit_(d) {
  var st = cleanStudent_(d.student), sid = String(d.submissionId || '');
  var result = markSubmission(ANSWER_KEY, d.answers || {});
  var cache = CacheService.getScriptCache();
  var begun = Number(cache.get('b_' + sid)) || Number(d.startedAt) || Date.now();
  var now = Date.now();
  var minutes = Math.round((now - begun) / 60000);
  var notes = [];
  var limit = (ANSWER_KEY.meta.durationMinutes || 30) + CONFIG.GRACE_MINUTES;
  if (minutes > limit) notes.push('Handed in ' + (minutes - limit + CONFIG.GRACE_MINUTES) + ' min after the time limit');
  if (d.autoSubmitted) notes.push('Time ran out');

  withLock_(function () {
    var sh = sheet_(CONFIG.RESULTS_SHEET, resultsHeader_());
    if (findRow_(sh, 'Submission ID', sid)) return;                // already logged (a retry)
    var attempt = attempts_(st.email) + 1;
    if (attempt > 1) notes.unshift('Attempt ' + attempt);
    sh.appendRow([new Date(now), st.last, st.first, st.nick, st.email, result.total, result.max, result.percent, result.grade]
      .concat(result.bySection.map(function (s) { return s.score; }))
      .concat([Math.min(minutes, 999), result.answered + ' / ' + result.partCount, Number(d.tabSwitches) || 0, Number(d.flagged) || 0, attempt, notes.join('; '), 'Sending…', sid]));
    var qs = sheet_(CONFIG.QUESTIONS_SHEET, questionsHeader_());
    qs.appendRow([new Date(now), st.last, st.first, result.total, result.grade].concat(result.byQuestion.map(function (q) { return q.score; })));
    var started = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.STARTED_SHEET);
    var r = started && findRow_(started, 'Submission ID', sid);
    if (r) started.getRange(r, 7).setValue('Yes');
  });

  cache.put('r_' + sid, JSON.stringify({ student: st, total: result.total, max: result.max, percent: result.percent, grade: result.grade,
    sections: result.bySection, minutes: minutes, notes: notes.join('; ') }), 21600);
  if (!CONFIG.SHOW_SOLUTIONS) delete result.solutions;
  return { ok: true, result: result };
}

var STARTED_HEADER_ = ['Started', 'Last name', 'First name', 'Nickname', 'Email', 'Submission ID', 'Handed in?'];
function questionsHeader_() { return ['Handed in', 'Last name', 'First name', 'Score', 'Grade'].concat(ANSWER_KEY.parts.map(function (p) { return p.full + ' (/' + p.marks + ')'; })); }
function resultsHeader_() {
  return ['Handed in', 'Last name', 'First name', 'Nickname', 'Email', 'Score', 'Out of', '%', 'Grade']
    .concat(ANSWER_KEY.sections.map(function (s) {
      var m = ANSWER_KEY.parts.filter(function (p) { return p.section === s.id; }).reduce(function (t, p) { return t + p.marks; }, 0);
      return s.name + ' (/' + m + ')';
    }))
    .concat(['Time (min)', 'Answered', 'Left the tab', 'Flagged', 'Attempt', 'Notes', 'Emailed', 'Submission ID']);
}

/* ----------------------------------------------------------- report */
function report_(d) {
  var sid = String(d.submissionId || ''), cache = CacheService.getScriptCache();
  if (cache.get('m_' + sid)) return { ok: true, duplicate: true };
  var info = cache.get('r_' + sid);
  info = info ? JSON.parse(info) : infoFromSheet_(sid);
  if (!info) return { ok: false, error: 'No marked test found for this submission.' };
  var st = info.student;
  var base = clean_(st.last) + '_' + clean_(st.first);
  var statsPdf = Utilities.newBlob(String(d.statsHtml), MimeType.HTML, base + '.html').getAs(MimeType.PDF).setName(base + ' - Results.pdf');
  var paperPdf = Utilities.newBlob(String(d.paperHtml), MimeType.HTML, base + '.html').getAs(MimeType.PDF).setName(base + ' - Marked test.pdf');
  var title = TEST_NAME_() + ' ' + ANSWER_KEY.meta.title;
  var name = st.first + ' ' + st.last + (st.nick ? ' (' + st.nick + ')' : '');

  var rows = (info.sections || []).map(function (s) {
    return '<tr><td style="padding:3px 10px;border:1px solid #ccd">' + esc_(s.name) + '</td><td style="padding:3px 10px;border:1px solid #ccd;text-align:right">' + s.score + ' / ' + s.max + '</td></tr>';
  }).join('');
  var teacherHtml = '<div style="font-family:Arial,sans-serif;color:#1F2536">' +
    '<h2 style="color:#1B2B5E;margin:0 0 6px">' + esc_(name) + ': ' + info.total + ' / ' + info.max + ' (' + info.percent + '%), grade ' + esc_(info.grade) + '</h2>' +
    '<p style="margin:0 0 10px">' + esc_(title) + '. Email: ' + esc_(st.email) + '. Time taken: ' + info.minutes + ' min.' + (info.notes ? ' <b>Notes: ' + esc_(info.notes) + '.</b>' : '') + '</p>' +
    '<table style="border-collapse:collapse">' + rows + '</table>' +
    '<p style="color:#5B6478">The results page and the marked test are attached as PDFs.</p></div>';
  MailApp.sendEmail({ to: CONFIG.TEACHER_EMAIL, subject: title + ': ' + name + ' — ' + info.total + '/' + info.max + ' (' + info.grade + ')',
    htmlBody: teacherHtml, replyTo: st.email, name: TEST_NAME_() + ' Test', attachments: [statsPdf, paperPdf] });

  if (CONFIG.SEND_TO_STUDENT && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(st.email)) {
    var studentHtml = '<div style="font-family:Arial,sans-serif;color:#1F2536;font-size:15px">' +
      '<p>Hi ' + esc_(st.nick || st.first) + ',</p>' +
      '<p>Here is your marked <b>' + esc_(title) + '</b>.</p>' +
      '<p style="font-size:20px;color:#1B2B5E"><b>' + info.total + ' / ' + info.max + ' (' + info.percent + '%) — Grade ' + esc_(info.grade) + '</b></p>' +
      '<table style="border-collapse:collapse">' + rows + '</table>' +
      '<p>Two PDFs are attached: your results, and your marked test with the correct answers. Go through the questions you missed before next lesson.</p>' +
      '<p>' + esc_(CONFIG.SIGN_OFF) + '</p></div>';
    MailApp.sendEmail({ to: st.email, subject: 'Your ' + title + ' results', htmlBody: studentHtml, replyTo: CONFIG.TEACHER_EMAIL,
      name: CONFIG.SENDER_NAME, attachments: [statsPdf.copyBlob().setName(statsPdf.getName()), paperPdf.copyBlob().setName(paperPdf.getName())] });
  }

  if (CONFIG.SAVE_TO_DRIVE) {
    var folder = folder_(CONFIG.DRIVE_FOLDER_NAME);
    folder.createFile(statsPdf.copyBlob().setName(statsPdf.getName()));
    folder.createFile(paperPdf.copyBlob().setName(paperPdf.getName()));
  }
  cache.put('m_' + sid, '1', 21600);
  withLock_(function () {
    var sh = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.RESULTS_SHEET);
    var r = sh && findRow_(sh, 'Submission ID', sid), c = sh && colOf_(sh, 'Emailed');
    if (r && c) sh.getRange(r, c).setValue(CONFIG.SEND_TO_STUDENT ? 'Student + teacher' : 'Teacher');
  });
  return { ok: true };
}

function infoFromSheet_(sid) {
  var sh = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.RESULTS_SHEET); if (!sh) return null;
  var r = findRow_(sh, 'Submission ID', sid); if (!r) return null;
  var head = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0], row = sh.getRange(r, 1, 1, sh.getLastColumn()).getValues()[0];
  function v(h) { return row[head.indexOf(h)]; }
  return { student: { last: v('Last name'), first: v('First name'), nick: v('Nickname'), email: v('Email') }, total: v('Score'), max: v('Out of'), percent: v('%'), grade: v('Grade'),
    sections: ANSWER_KEY.sections.map(function (s, i) { var h = head[9 + i]; return { name: s.name, score: row[9 + i], max: Number(String(h).replace(/.*\/(\d+)\).*/, '$1')) }; }),
    minutes: v('Time (min)'), notes: v('Notes') };
}

/* -------------------------------------------------- setup + helpers */
/** Run once from the editor: grants permissions, checks the answer key and sends you a test email. */
function authorise() {
  var r = markSubmission(ANSWER_KEY, {});
  MailApp.sendEmail(CONFIG.TEACHER_EMAIL, TEST_NAME_() + ' test server: permissions OK',
    'Your Apps Script can send email. Answer key loaded: ' + ANSWER_KEY.meta.testId + ' (' + r.max + ' marks, ' + ANSWER_KEY.parts.length + ' questions). The Started, Results and By question tabs are ready. Now deploy it as a web app (README step 2), then open your test page with ?check at the end of the address.');
  if (CONFIG.SAVE_TO_DRIVE) folder_(CONFIG.DRIVE_FOLDER_NAME);
  sheet_(CONFIG.STARTED_SHEET, STARTED_HEADER_);
  sheet_(CONFIG.RESULTS_SHEET, resultsHeader_());
  sheet_(CONFIG.QUESTIONS_SHEET, questionsHeader_());
  var pdf = Utilities.newBlob('<p>PDF test</p>', MimeType.HTML, 't.html').getAs(MimeType.PDF);
  Logger.log('PDF conversion OK (' + pdf.getBytes().length + ' bytes). Total marks: ' + r.max);
}

function cleanStudent_(s) {
  s = s || {};
  function c(x, n) { return String(x == null ? '' : x).replace(/[\u0000-\u001f]/g, '').replace(/^[=+\-@]+/, '').trim().slice(0, n); }  // stop formula injection into the sheet
  return { first: c(s.first, 60), last: c(s.last, 60), nick: c(s.nick, 60), email: c(s.email, 120).toLowerCase() };
}
function attempts_(email) {
  var sh = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(CONFIG.RESULTS_SHEET);
  if (!sh || sh.getLastRow() < 2) return 0;
  var c = colOf_(sh, 'Email'); if (!c) return 0;
  var e = String(email).toLowerCase();
  return sh.getRange(2, c, sh.getLastRow() - 1, 1).getValues().filter(function (r) { return String(r[0]).toLowerCase() === e; }).length;
}
function sheet_(name, header) {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sh = ss.getSheetByName(name) || ss.insertSheet(name);
  if (sh.getLastRow() === 0) {
    sh.appendRow(header); sh.setFrozenRows(1);
    sh.getRange(1, 1, 1, header.length).setFontWeight('bold').setBackground(HEAD.navy).setFontColor(HEAD.white).setWrap(true);
  }
  return sh;
}
function colOf_(sh, title) { var h = sh.getRange(1, 1, 1, Math.max(1, sh.getLastColumn())).getValues()[0]; var i = h.indexOf(title); return i < 0 ? 0 : i + 1; }
function findRow_(sh, title, value) {
  var c = colOf_(sh, title); if (!c || sh.getLastRow() < 2 || !value) return 0;
  var vals = sh.getRange(2, c, sh.getLastRow() - 1, 1).getValues();
  for (var i = vals.length - 1; i >= 0; i--) if (String(vals[i][0]) === String(value)) return i + 2;
  return 0;
}
function withLock_(fn) { var lock = LockService.getScriptLock(); lock.waitLock(30000); try { return fn(); } finally { lock.releaseLock(); } }
function folder_(name) { var it = DriveApp.getFoldersByName(name); return it.hasNext() ? it.next() : DriveApp.createFolder(name); }
function clean_(s) { return String(s || 'Unknown').replace(/[^\w\- ]+/g, '').trim().replace(/\s+/g, '-'); }
function esc_(s) { return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]; }); }
function json_(o) { return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON); }
